/* Generated By:JavaCC: Do not edit this line. ESFParserConstants.java */
package org.lwes.db;

public interface ESFParserConstants {

  int EOF = 0;
  int ID = 10;

  int DEFAULT = 0;
  int IN_LINE_COMMENT = 1;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"#\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"\\r\\n\"",
    "<token of kind 9>",
    "<ID>",
    "\"{\"",
    "\"}\"",
    "\";\"",
  };

}
